### PR TITLE
Proposed agenda

### PR DESCRIPTION
**Pull request by arfon**
Still needs some work but looks reasonable to me. We need to reach out to speakers soon...

### CODE REVIEW

**Comment by arfon** [comment]
/ cc @eteq @jegpeek incase you have a chance to review too.

**Comment by eteq** [comment]
@arfon - this all seems good to me except one thing: is Lunch going to be the "Azafran bag lunch" approach, or the "go-to-azafran-and-wait-in-line" version?  If the latter, having it right at noon might lead to a substantial traffic jam, so 12:15 or 12:30 might be better.

**Comment by arfon** [comment]
>"Azafran bag lunch" 

Thanks @eteq - it's going to be ☝️ this one.

**Comment by jegpeek** [comment]
Sorry I am just getting to this! Do we want something on scientific use cases? Big data vs. complex pipelines? Rare power users vs. broader engagement?

**Pull request merged**
